version: "3"
services:
  composer:
    build: ./docker/php/8.3
    entrypoint: composer
    working_dir: /home/alpine/app
    volumes:
      - .:/home/alpine/app

  composer82:
    build: ./docker/php/8.2
    entrypoint: composer
    working_dir: /home/alpine/app
    volumes:
      - .:/home/alpine/app

  php:
    build: ./docker/php/8.3
    entrypoint: php
    working_dir: /home/alpine/app
    volumes:
      - .:/home/alpine/app
