name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: docker-compose run composer install

      - name: Test
        run: docker-compose run composer run test

      - name: Analyse
        run: docker-compose run composer run analyse

      - name: Lint
        run: docker-compose run composer run lint

      - name: Audit
        run: docker-compose run composer run check

      - name: Check modern code
        run: docker-compose run composer run scan

      - name: Check updates
        run: docker-compose run composer run updates

  test_82:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: docker-compose run composer82 install

      - name: Test
        run: docker-compose run composer82 run test

      - name: Analyse
        run: docker-compose run composer82 run analyse

      - name: Lint
        run: docker-compose run composer82 run lint

      - name: Audit
        run: docker-compose run composer82 run check

      - name: Check modern code
        run: docker-compose run composer82 run scan

      - name: Check updates
        run: docker-compose run composer82 run updates
